# Bundles the markdown files listed in lore/manifest.json into lore-data.js,
# a plain script the page can load directly with a <script> tag. Along the
# way, each entry's markdown is parsed into a title + a list of blocks
# (paragraphs and "#"-headings), and inline markdown (**bold**,
# *italic*/_italic_) is converted into <strong>/<em> tags -- script.js
# renders those tags directly rather than parsing markdown at runtime.
#
# Why bundle at all: browsers block fetch() of local files opened via
# file:// (double-click), so the site can't read the .md files at runtime
# without a server. Running this script after editing any .md file (or
# manifest.json) regenerates lore-data.js so the page works offline with no
# server needed.
#
# Usage: right-click > "Run with PowerShell", or from a terminal:
#   powershell -ExecutionPolicy Bypass -File build-lore.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$loreDir = Join-Path $root "lore"
$manifestPath = Join-Path $loreDir "manifest.json"

# Converts **bold**, __bold__, *italic*, and _italic_ spans into
# <strong>/<em> tags. Everything else is left as plain text -- script.js
# renders these tags directly via a small tag-aware tokenizer instead of
# innerHTML, so raw "&", "<", ">" in the prose don't need escaping here.
function ConvertTo-InlineHtml {
  param([string]$Text)
  $html = [regex]::Replace($Text, '\*\*(.+?)\*\*', '<strong>$1</strong>')
  $html = [regex]::Replace($html, '__(.+?)__', '<strong>$1</strong>')
  $html = [regex]::Replace($html, '\*(.+?)\*', '<em>$1</em>')
  $html = [regex]::Replace($html, '(?<!\w)_(.+?)_(?!\w)', '<em>$1</em>')
  return $html
}

function ConvertTo-EntryCode {
  param([string]$Filename)
  if ($Filename -match '^0*(\d+)') {
    return "ENTRY-{0:D3}" -f [int]$Matches[1]
  }
  return "ENTRY-???"
}

$manifest = Get-Content -Path $manifestPath -Raw | ConvertFrom-Json

$parts = foreach ($filename in $manifest) {
  $filePath = Join-Path $loreDir $filename
  if (-not (Test-Path $filePath -PathType Leaf)) {
    throw "manifest.json lists '$filename' but $filePath does not exist"
  }

  $raw = [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)
  $text = ($raw -replace "`r`n", "`n").Trim()
  $lines = $text -split "`n"

  $title = [System.IO.Path]::GetFileNameWithoutExtension($filename)
  $bodyStart = 0
  if ($lines.Count -gt 0 -and $lines[0].TrimStart() -match '^#') {
    $title = ($lines[0] -replace '^#+\s*', '').Trim()
    $bodyStart = 1
  }

  $bodyText = ""
  if ($bodyStart -lt $lines.Count) {
    $bodyText = ($lines[$bodyStart..($lines.Count - 1)] -join "`n").Trim()
  }

  # Each blank-line-separated block becomes either a heading (if it starts
  # with 1-6 "#" characters) or a paragraph.
  $paragraphs = @(
    [regex]::Split($bodyText, '\n\s*\n') |
      ForEach-Object { ($_ -replace '\s+', ' ').Trim() } |
      Where-Object { $_ -ne '' } |
      ForEach-Object {
        if ($_ -match '^(#{1,6})\s+(.*)$') {
          [PSCustomObject]@{ tag = "h$($Matches[1].Length)"; html = ConvertTo-InlineHtml $Matches[2].Trim() }
        } else {
          [PSCustomObject]@{ tag = 'p'; html = ConvertTo-InlineHtml $_ }
        }
      }
  )

  $entry = [PSCustomObject]@{
    code  = ConvertTo-EntryCode $filename
    title = ConvertTo-InlineHtml $title
    body  = $paragraphs
  }
  $entry | ConvertTo-Json -Compress -Depth 5
}

$json = "[`n  " + ($parts -join ",`n  ") + "`n]"

$output = @"
// AUTO-GENERATED by build-lore.ps1 -- do not edit by hand.
// Edit the markdown files in lore/ (and manifest.json if you add/remove
// entries), then rerun build-lore.ps1 to regenerate this file.
// title/body strings may contain <strong>/<em> tags converted from
// markdown -- script.js renders these directly.
const LORE_ENTRIES = $json;
"@

$outPath = Join-Path $root "lore-data.js"
Set-Content -Path $outPath -Value $output -Encoding utf8

Write-Host "Wrote lore-data.js with $($manifest.Count) entries."
