---
---
// Generated by Jekyll from the markdown files in _lore/ -- edit those, not
// this file. Entries are listed in filename order; add `published: false` to
// an entry's front matter to hide it. Each entry's html is kramdown's output,
// which script.js types out in the archive terminal.
{% assign entries = site.lore | sort: "relative_path" -%}
const LORE_ENTRIES = [
{%- for entry in entries %}
  { "slug": {{ entry.slug | jsonify }}, "html": {{ entry.content | jsonify }} }{% unless forloop.last %},{% endunless %}
{%- endfor %}
];
